const MyObjectsList = {
  lostObjects: [
    {
      id: "1",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Copo Stanley",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvef-li3j1cjkr20af5",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvg6-li3j1c877oxy1b",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvfr-li3j1c8r6vzj6c",
        // "https://down-br.img.susercontent.com/file/sg-11134201-7qvfr-li3j1c8r6vzj6c",
      ],
    },
    {
      id: "2",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Copo Stanley",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvef-li3j1cjkr20af5",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvg6-li3j1c877oxy1b",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvfr-li3j1c8r6vzj6c",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvfr-li3j1c8r6vzj6c",
      ],
    },
    {
      id: "3",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Copo Stanley",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvef-li3j1cjkr20af5",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvg6-li3j1c877oxy1b",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvfr-li3j1c8r6vzj6c",
        "https://down-br.img.susercontent.com/file/sg-11134201-7qvfr-li3j1c8r6vzj6c",
      ],
    },
    {
      id: "4",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 4",
      brand: "Acme",
      model: "XYZ",
      color: "Vermelho",
      characteristics: ["Brilhante"],
      place: "CEUB",
      date: "05/11/2023",
      time: "12:00",
      info: "Sei lá mano",
      imgUrl: [],
    },
    {
      id: "5",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 5",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "6",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 6",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "7",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 7",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "8",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 8",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "9",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 9",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "10",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 10",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "11",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 11",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "12",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 12",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "13",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 13",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "14",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 14",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
    {
      id: "15",
      situation: "lost",
      // ownerId: "Cleiton Fernandes",
      object: "Objeto 15",
      brand: "Stanley",
      model: "SVT40",
      color: "Branco",
      characteristics: ["Rachado", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Devo ter perdido na cantina, comi numa mesa na frente do microondas.",
      imgUrl: [],
    },
  ],
  foundObjects: [
    {
      id: "1",
      situation: "found",
      // ownerId: "Cleiton Fernandes",
      object: "Relógio Rolex",
      brand: "Rolex",
      model: "",
      color: "Branco",
      characteristics: ["Rachado ao meio", "Sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Achei perto dos microondas da cantida.",
      imgUrl: [
        "https://d2r9epyceweg5n.cloudfront.net/stores/002/644/199/products/screenshot_20221208-171415_chrome1-1e4157f8b43dd558b116705316736080-640-0.jpg",
      ],
    },
    {
      id: "2",
      situation: "found",
      // ownerId: "Cleiton Fernandes",
      object: "Relógio Rolex",
      brand: "Stanley",
      model: "",
      color: "Branco",
      characteristics: ["rachado ao meio", "sujo"],
      place: "IESB",
      date: "08/09/2023",
      time: "18:30",
      info: "Achei perto dos microondas da cantida.",
      imgUrl: [],
    },
  ],
};

export default MyObjectsList;
